configfile: "config.yaml"


#cores: 16 
cores: 32
#cores: all


keep-going: true
show-failed-logs: true
keep-incomplete: false # true for development


use-conda: true
conda-frontend: mamba


default-resources:
  - tmpdir='/cluster/work/users/cmkobel/tmpdir'
 #- tmpdir='/mnt/hpccs01/scratch/microbiome/kobel'
 
 