# configfile: "config.yaml"
  

cores: all # good guy 
#cores: 64 # not a good guy 
# I think The Epycs have 64 physical cores which become 128 with hyperthreading

keep-going: true 
show-failed-logs: true

# Flip these for debugging:
keep-incomplete: true # true for development/debugging
rerun-triggers: "mtime" 

use-conda: true
conda-frontend: mamba
conda-prefix: '~/.mspipeline1/conda'

# In the event that TMPDIR is not set on the local node, use this:
# default-resources:
#   - tmpdir='/cluster/work/users/cmkobel/tmpdir'




# Local setup for a typical workstation
# resources:
#   - mem_mb=184320 # johans

# Giant swapping
resources:
  - mem_mb=453632

# # using swap
# resources:
#   - mem_mb=190000 # johans

