local-cores: 8 # front end / head node cores
cores: 2048 # cluster cores
jobs: 1000 # max parallel jobs
keep-going: false
#rerun-incomplete: true
latency-wait: 120
keep-incomplete: false # true for debugging investigations

# This one could be cool to have working 
show-failed-logs: true


# ---- Conda/Mamba ----
use-conda: true
conda-frontend: 'mamba'
#conda-prefix: "conda_base/" # Much better to use the $SNAKEMAKE_CONDA_PREFIX instead, as all workflows can then use the same envs.



# ---- Sigma2 Saga SLURM specifics ----

cluster-cancel: "scancel"

cluster:
  mkdir -p logs/old/ &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=ms1_{rule}_{wildcards}
    --output=logs/{jobid}-{rule}.out.log
    --error=logs/{jobid}-{rule}.err.log
    --time={resources.runtime}
    --account=nn9864k
    --partition={resources.partition}
    



default-resources:
  - mem_mb=1024
  - disk_mb=1024
  - runtime='12:00:00'
  - tmpdir='$SCRATCH'
  #- tmpdir='/cluster/work/users/cmkobel/tmp' # We're already at userwork, so that won't be faster
  - partition=normal
  
  

#set-resources:
#  - annotate:mem_mb=65536
#  - philosopher_database:mem_mb=65536 # use mem_mb, not mem
#  - msfragger:mem_mb=515537 # max on gdk is 515538
#  - msfragger:partition=bigmem
#  - ionquant:mem_mb=65536
# update: Moved these into the snakefile



# ---- Old unused stuff ----
#cluster: "sbatch -A {cluster.account} -t {cluster.time} -p {cluster.partition} --mem {cluster.mem} --error={cluster.error} --output={cluster.output}"
# drmaa: "
#     --mem={cluster.mem_mb} 
#     --cpus-per-task={cluster.cpus-per-task} 
#     --time={cluster.time} 
#     --account={cluster.account}
#     --error={cluster.error} 
#     --output={cluster.output}
# "
#retries: 2
#cluster: "sbatch --account {cluster.account} --time {cluster.time} --mem {cluster.mem_mb} --error={cluster.error} --output={cluster.output}"

# [--local-cores N] 
#local-cores: 2
#configfile: "configs/workflow.yaml"
#configfile: "config.yaml"
# [--snakefile FILE] 

# While still being possible, cluster configuration has been deprecated by the introduction of Profiles. (https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles)
#cluster-config: "profiles/slurm/cluster.yaml" 


# ---- Singularity ----
#use-singularity: True
#singularity-prefix: "/faststorage/home/cmkobel/singularity_images/"
