---
title: "`r basename(getwd())`"
#author: "Carl Mathias Kobel / MEMO"
#license: GNU GPL v3

subtitle: "LFQ-MBR QC"
date: "`r Sys.time()`"
output:
  html_document:
    toc: false
    toc_depth: 2
  #prettydoc::html_pretty:
    #theme: cayman
    #highlight: github
editor_options: 
  chunk_output_type: console
#css: "max-width: 5000px; margin: auto; padding: 1em; line-height: 20px"
---



`r paste("This report was generated in", getwd())`

```{r echo=FALSE, message=F, warning=F}
 
#Dependencies
library(tidyverse)
#library(prettydoc)
library(DT)





```


```{r echo=FALSE, message=F, warning=F}
# Read data
# Basic setup


# For development:
options(vsc.dev.args = list(width = 600, height = 700, res = 150))

setwd("/cluster/work/users/cmkobel/MS-pipeline1-split-output/220506_digesta_puchun") # For development
#setwd("/cluster/work/users/cmkobel/MS-pipeline1-split-output/220506_DnnT6S_carl") # For development




# Since we're already inside the batch directory, we can read it as the basename of the WD:

batch = getwd() %>% basename()
#batch


#paste("this is the getwd")
#paste(getwd())


df_metadata = try({
    read_delim(paste0("metadata.tsv")) %>%
        select(-index) %>% rename(stem = basename)
})

```

```{r echo=FALSE, message=F, warning=F}
# Read the rest of the data. No joining, just a bit of cleaning.

#df_db_stats = try({
#    read_delim(paste0("db_stats.tsv"))
#})

df_db_stats = try({
    read_tsv("db_stats_seqkit.tsv") %>% 
        mutate(rank = n():1) %>% 
        mutate(basename = basename(file)) %>% 
        select(file, basename, everything())
})

df_manifest = try({
    read_tsv(paste0("fragpipe/", batch, ".manifest"), col_names = c("path", "experiment", "bioreplicate", "type"))
})

df_protein = try({
    read_tsv(paste0("fragpipe/combined_protein.tsv"))
})

df_workflow = try({
    read_delim(paste0("fragpipe/fragpipe_modified.workflow"), delim = "=", comment = "#", col_names = c("name", "value"))
})

df_fragpipe_scans = try({
    read_delim(paste0("fragpipe/stats_fragpipe_scans.tsv"), delim = ": Scans = ", col_names = c("path", "n_scans")) %>% 
    mutate(stem = basename(path) %>% str_remove("\\.d$")) %>% 
    left_join(df_metadata, by = "stem")
})


# Not sure if I trust the sometimes random order of this stuff.
# Non-rigorous counting of psms


# df_fragpipe_psms_order = try({
#     tibble(lines = read_lines("fragpipe/stats_fragpipe_psms_order.tsv")) 
#     #extract(lines, c("ions", "peptides", "proteins", "psms"), "time=\"[0-9:]+\" level=info msg=\"Final report numbers after FDR filtering, and post-processing\" ions=(\\d+) peptides=(\\d+) proteins=(\\d+) psms=(\\d+)")

# })

# df_fragpipe_psms = try({
#     tibble(lines = read_lines("fragpipe/stats_fragpipe_psms.tsv")) %>% 
#     extract(lines, c("ions", "peptides", "proteins", "psms"), "time=\"[0-9:]+\" level=info msg=\"Final report numbers after FDR filtering, and post-processing\" ions=(\\d+) peptides=(\\d+) proteins=(\\d+) psms=(\\d+)")

# })
    
# Check that there is the same number of rows in the tables that will blindly be joined.
#stopifnot(dim(df_fragpipe_scans)[[1]] == dim(df_fragpipe_psms)[[1]])


# Rigorous counting of psms
df_psm = try({

    tibble(File = Sys.glob("fragpipe/*/psm.tsv")) %>% 
    extract(File, "sample", "fragpipe/(.+)/psm.tsv", remove = FALSE)  %>% # We don't really need this one, but it is OK to have I guess.
    mutate(Data = lapply(File, read_lines, skip = 1))  %>% 
    mutate(n_psms = lengths(Data)) %>% 
    select(-Data)

    # unnest(Data)  %>% 

    # extract(`Spectrum File`, "stem", "interact-(.+)\\.pep\\.xml", remove = F) %>% 
    # left_join(df_metadata, by = "stem")
})


#df_fragpipe_stats = bind_cols(df_fragpipe_scans, df_fragpipe_psms)


cells = list() # To not mess up the environment.



```


## Workflow

Selected keys from the fragpipe workflow used.

```{r echo=FALSE, message=F, warning=F}
# Workflow

df_workflow %>% 
    filter(str_detect(name, "slice|description|cmd-opts|ionfdr|num_threads|db\\-path")) %>%
    drop_na(value)  %>% 

    group_by(name) %>% 
    mutate(rank = n():1) %>% 
    filter(rank == 1) %>% 
    select(-rank) %>% 
    datatable(class = "cell-border stripe")





```


## Metadata
```{r echo=FALSE, message=F, warning=F}

try({
    df_metadata %>% 
        #arrange(sample) %>% 
        datatable(class = "cell-border stripe")

    # extract workflow description as well
})
```

## Database
```{r echo=FALSE, message=F, warning=F}

try({

    cells$db = list()
    cells$db$`number of genes` = (df_db_stats %>% filter(name == "n_records_in_db"))$value
    cells$db$`number of files in db_glob` = (df_db_stats %>% filter(name == "db_glob_read"))$value %>% str_split(" ") %>% unlist() %>% length()




    as_tibble(cells$db) %>% 
        pivot_longer(everything(), values_transform = as.character) %>% 
        #mutate(name = str_replace(name, "_", " ")) %>%
        datatable(class = "cell-border stripe")
    
#TODO: Somehow add length in bp?
# And add some more parameters.

# NEW stats file:



# Glob statistics
df_db_stats_globs = df_db_stats %>% 
    filter(rank > 1)

df_db_stats %>% 
    select(-rank, -file) %>% 
    datatable(class = "cell-border stripe")
    


# Final statistics
df_db_stats_final = df_db_stats %>% 
    filter(rank == 1)

df_db_stats_final %>% 
    select(-file, -rank) %>% 
    mutate_all(as.character)  %>% 
    pivot_longer(everything())  %>% 
    datatable()


})
```


## Identification rate
```{r echo=FALSE, message=F, warning=F}

try({
    # spectrum_counts = df_psm %>% 
    #     group_by(sample, stem) %>% 
    #     summarize(n_psms = n())
    #     #mutate(stem = str_remove_all(`Spectrum File`, "^interact-|\\.pep\\.xml$"))
    #     #select(-`Spectrum File`) %>% 
        
    #     #select(sample, n_psms)
        
    # # testregex = str_match_all(spectrum_counts$`Spectrum File`, "interact-(?<sample>.+)\\.pep\\.xml")

    # join_scans_psms = df_fragpipe_scans %>% 

    #     # Extract the stem from the full path
    #     mutate(stem = basename(path)) %>%
    #     mutate(stem = str_remove(stem, "\\.d$")) %>% 
    #     left_join(spectrum_counts) %>% 
    #     mutate(quotient = n_psms/n_scans) %>% 
        
    #     select(n_scans, n_psms, quotient, stem)

    



    ## restart:    

    identification_rate = df_fragpipe_scans %>% 
        left_join(df_psm, by = "sample") %>% 
        select(sample, stem, barcode, n_scans, n_psms) %>% 
        mutate(quotient = n_psms/n_scans) 

    identification_rate %>% 
        select(-barcode) %>%
        mutate(quotient = signif(quotient, 4)) %>% 
        datatable(class = "cell-border stripe")


# Too bad I couldn't figure out a nice way of adding the ions and peptides, but whatever, guess I can always just read the individual files or something.

})

```

```{r echo=FALSE, message=F, warning=F}

# Plot 
try({
    # Useful to have writte to disk.
    identification_rate %>%
        write_tsv("identification_rate.tsv")

    identification_rate %>% 
        ggplot(aes(n_scans, n_psms, color = quotient, label = sample)) +
        geom_abline(slope = identification_rate$quotient %>% median(), alpha = 0.4) +
        geom_point(size = 2) +
        scale_color_viridis_b() +
        geom_text(color = "#000000", vjust = 0, hjust = 0, alpha = 0.6, size = 3, check_overlap = T) +
        #geom_smooth(method = "lm") +
        
        labs(
            title = "Identification rate",
            caption = "quotient = n_psms/n_scans\nThe slope represents the median quotient.") 
            

    
})


```


## Proteins


```{r echo=FALSE, message=F, warning=F}

try({

    df_indistinguishable = df_protein %>%
        #head(1001) %>%
        #group_by(Protein) %>%
        mutate(
            #indistinguishable = is.na(`Indistinguishable Proteins`),
            #n_indistinguishable = str_split(`Indistinguishable Proteins`, ", ") %>% lengths(),
            
            n_indistinguishable = case_when(
                is.na(`Indistinguishable Proteins`) ~ as.integer(0),
                TRUE ~ str_split(`Indistinguishable Proteins`, ", ") %>% lengths(),
            )
        )


    df_indistinguishable %>%
        ggplot(aes(n_indistinguishable)) +
        geom_histogram() +
        #scale_x_log10() +
        scale_y_log10() +
        labs(
            title = "Proteins are indistinguishable",
            caption = "This is a histogram. Vertical axis is visually log-scaled."
        )


    # TODO: Okay, der er masser af andre ting jeg kunne gøre og det ville være fint at have en oversigt over prøverne, men nu tænker jeg lige at starte med at prøve at smide rapporten ind i snakemake.


# Generic protein statistics
df_protein %>% 
    select(`Protein`, `Protein Length`, `Protein Probability`, `Top Peptide Probability`, `Combined Total Peptides`, `Combined Spectral Count`, `Combined Unique Spectral Count`, `Combined Total Spectral Count`) %>%
    #glimpse()

    pivot_longer(-Protein) %>% 

    ggplot(aes(value)) + 
    geom_histogram() +
    facet_wrap(~name, scales = "free") + 
    labs(
        title = "Protein statistics"
    )


protein_intensities = df_protein %>% 
    select(`Protein`, ends_with("Intensity")) %>% 
    select(-contains("MaxLFQ"))


protein_intensities_long = protein_intensities %>% 
    pivot_longer(-Protein) %>% 
    mutate(sample = str_remove(name, " Intensity"))   # Potentially unstable to add metadata order?
    


protein_intensities_long %>% 
    ggplot(aes(value)) + 
    geom_histogram() + 
    scale_x_log10() +
    facet_wrap(~sample) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +

    labs(title = "Protein intensities per sample", 
        caption = "Horizontal scale is visually log-transformed.")


# Commented out because it is too hard to tell the samples apart.
# protein_intensities_long %>% 
#     ggplot(aes(value, color = sample)) + 
#     geom_density(alpha = 0, size = .05) + 
#     scale_x_log10()

})
```



## Hierarchical clustering

Dendrogram on protein intensities between samples.
```{r echo=FALSE, message=F, warning=F}

options(vsc.dev.args = list(width = 600, height = 700, res = 70))

# protein labels: wrong
# run_hclust = protein_intensities %>% 
#     column_to_rownames("Protein") %>% 
#     dist() %>% 
#     hclust() 

protein_intensities_altwide = protein_intensities_long %>% 
    select(-name) %>% 
    pivot_wider(id_cols = sample, names_from = Protein, values_from = value) 

run_hclust = protein_intensities_altwide %>% 
    column_to_rownames("sample") %>% 
    dist() %>% 
    hclust()

run_hclust %>% 
    plot(sub = "", xlab = "Euclidean distance")
 

```



## PCA

### Unscaled
```{r echo=FALSE, message=F, warning=F}

options(vsc.dev.args = list(width = 600, height = 700, res = 200))

# without scaling
run_pca = protein_intensities_altwide %>% 
    column_to_rownames("sample") %>% 
    prcomp(scale. = F)

# Scree
plot_a = run_pca$sdev^2 %>%
    tibble(
        variance = (. / sum(.)) * 100,
        component = paste0("PC", 1:length(variance))) |>
    
    mutate(component = fct_reorder(component, -variance)) |> 
    ggplot(aes(component, variance)) + 
    geom_point() +
    labs(title = "Scree", 
         y = "variance [%]") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))



plot_b = run_pca$x |> 
    as_tibble(rownames = "sample") |> 

    ggplot(aes(PC1, PC2, color = PC3, label = sample)) + 
    geom_point() +
    #geom_text(aes(label = sample), nudge_x = .3, nudge_y = .3, hjust = 0, vjust = 0, size = 2) +
    geom_text(color = "#000000", vjust = 0, hjust = 0, alpha = 0.6, size = 2, check_overlap = T) +
    scale_color_viridis_c() +
    coord_fixed() +
    labs(title = "Principal component analysis", 
        subtitle = "Protein intensities")
    


plot_a
plot_b



```



### Scaled
```{r echo=FALSE, message=F, warning=F}




# with scaling:
oopsmat = protein_intensities_altwide %>% 
    column_to_rownames("sample") 
run_pca_scaled = oopsmat[ , which(apply(oopsmat, 2, var) != 0)] %>%  
    prcomp(scale. = T)

# Scree
plot_a_scaled = run_pca_scaled$sdev^2 %>%
    tibble(
        variance = (. / sum(.)) * 100,
        component = paste0("PC", 1:length(variance))) |>
    
    mutate(component = fct_reorder(component, -variance)) |> 
    ggplot(aes(component, variance)) + 
    geom_point() +
    labs(title = "Scree", 
         y = "variance [%]") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))



plot_b_scaled = run_pca_scaled$x |> 
    as_tibble(rownames = "sample") |> 
    
    ggplot(aes(PC1, PC2, color = PC3, label = sample)) + 
    geom_point() +
    #geom_text(aes(label = sample), nudge_x = .3, nudge_y = .3, hjust = 0, vjust = 0, size = 2) +
    geom_text(color = "#000000", vjust = 0, hjust = 0, alpha = 0.6, size = 2, check_overlap = T) +
    scale_color_viridis_c() + 
    coord_fixed() +
    labs(title = "Principal component analysis", 
        subtitle = "Scaled protein intensities")
    


plot_a_scaled
plot_b_scaled
```



This report was generated with [MS-pipeline1](https://github.com/cmkobel/MS-pipeline1), developed by [Carl Mathias Kobel](https://github.com/cmkobel).