---
title: "`r head(tail(unlist(strsplit(getwd(), '/')), 2), 1)`"
subtitle: "LFQ-MBR QC"
date: "`r Sys.time()`"
output:
  html_document:
    toc: false
    toc_depth: 2
  #prettydoc::html_pretty:
    #theme: cayman
    #highlight: github
editor_options: 
  chunk_output_type: console
#css: "max-width: 5000px; margin: auto; padding: 1em; line-height: 20px"
---

`r paste("This report was generated in", getwd())`

```{r echo=FALSE, message=F, warning=F}
 
#Dependencies
library(tidyverse)
#library(prettydoc)
library(DT)




```


# Read data
```{r echo=FALSE, message=F, warning=F}

setwd("~/Downloads/output 8")
batch = "220506_digesta_puchun"




df_metadata = tryCatch({read_delim(paste0(batch, "/metadata.tsv")) %>% select(-index) %>% rename(stem = basename)})
df_db_stats = tryCatch({read_delim(paste0(batch, "/db_stats.tsv"))})
df_manifest = tryCatch({read_delim(paste0(batch, "/fragpipe/", batch, ".manifest"), col_names = c("path", "experiment", "bioreplicate", "type"))})
df_protein = tryCatch({read_delim(paste0(batch, "/fragpipe/combined_protein.tsv"))})
df_workflow = tryCatch({read_delim(paste0(batch, "/fragpipe/fragpipe_modified.workflow"), delim = "=", comment = "#")})
df_fragpipe_stats = tryCatch({read_delim(paste0(batch, "/fragpipe/fragpipe_stats.tsv"), delim = ": Scans = ", col_names = c("path", "n_scans"))})
df_psm = tryCatch({read_delim(paste0(batch, "/fragpipe/experiment/psm.tsv"))})




```


# Metadata
```{r}

df_metadata %>% 
    #arrange(sample) %>% 
    datatable(class = "cell-border stripe")

```

# Database
```{r}
tryCatch({
    
    db_stats_parsed = list()
    db_stats_parsed$n_genes = (df_db_stats %>% filter(name == "n_records_in_db"))$value
    db_stats_parsed$n_db_glob = (df_db_stats %>% filter(name == "db_glob_read"))$value %>% str_split(" ") %>% unlist() %>% length()
    

    as_tibble(db_stats_parsed) %>% 
        pivot_longer(everything(), values_transform = as.character) %>% 
        datatable(class = "cell-border stripe")
    
#TODO: Somehow add length in bp?

})
```


# Identification rate
```{r}

spectrum_counts = df_psm %>% 
    group_by(`Spectrum File`) %>% 
    summarize(n_psms = n()) %>%
    mutate(stem = str_remove_all(`Spectrum File`, "^interact-|\\.pep\\.xml$"))
    #select(-`Spectrum File`) %>% 
    
    #select(sample, n_psms)
    
#testregex = str_match_all(spectrum_counts$`Spectrum File`, "interact-(?<sample>.+)\\.pep\\.xml")

join_scans_psms = df_fragpipe_stats %>% 
    mutate(stem = basename(path)) %>%
    mutate(stem = str_remove(stem, "\\.d$")) %>% 
    #select(-path) %>% 
    #select(stem, everything()) %>% 
    left_join(spectrum_counts) %>% 
    mutate(quotient = n_psms/n_scans) %>% 
    
    select(n_scans, n_psms, quotient, stem)

identification_rate = df_metadata %>% 
    left_join(join_scans_psms, by = "stem")

identification_rate %>% 
    select(-barcode) %>% 
    datatable(class = "cell-border stripe")



identification_rate %>% 
    ggplot(aes(n_scans, n_psms, color = quotient, label = sample)) +
    geom_abline(slope = identification_rate$quotient %>% median(), alpha = 0.4) +
    geom_point(size = 2) +
    scale_color_viridis_b() +
    geom_text(color = "black", vjust = 0, hjust = 0, alpha = 0.5, size = 3, check_overlap = T) +
    #geom_smooth(method = "lm") +
    
    labs(
        title = "Identification rate",
        caption = "quotient = n_psms/n_scans\nThe slope represents the median quotient.") 
           



```


# Proteins