# [--snakefile FILE] 
cores: 2048
# [--local-cores N] 
#local-cores: 2
#configfile: "configs/workflow.yaml"
configfile: "config.yaml"
jobs: 8


# [--directory DIR] 
keep-going: true 
#batch: "run_main=1/500" # removed due to warning: --batch may not be combined with --forceall, because recomputed upstream jobs in subsequent batches may render already obtained results outdated.

rerun-incomplete: true
# [--shadow-prefix DIR] 
# [--reason] 
latency-wait: 120
# [--max-jobs-per-second MAX_JOBS_PER_SECOND] 
# [--greediness GREEDINESS] 
# [--runtime-profile FILE] 
show-failed-logs: false
# drmaa: "
#     --mem={cluster.mem} 
#     --cpus-per-task={cluster.cpus-per-task} 
#     --time={cluster.time} 
#     --account={cluster.account}
#     --error={cluster.error} 
#     --output={cluster.output}
# "

cluster-config: "profiles/slurm/cluster.yaml" 
cluster: "sbatch --account {cluster.account} --time {cluster.time} --partition {cluster.partition} --mem {cluster.mem} --error={cluster.error} --output={cluster.output}"
#cluster: "sbatch -A {cluster.account} -t {cluster.time} -p {cluster.partition} --mem {cluster.mem} --error={cluster.error} --output={cluster.output}"


jobname: "{name}.{jobid}.snakejob.sh" 
use-conda: true
conda-prefix: "conda_base/"
#use-singularity: True
#singularity-prefix: "/faststorage/home/cmkobel/singularity_images/"
cluster-cancel: "scancel"

